apiVersion: v1
kind: Namespace
metadata: 
  name: my-namespace
---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: my-deployment
  namespace: my-namespace
spec: 
  replicas: 3
  selector: 
    matchLabels: 
      app: my-apps
  template: 
    metadata:
      labels:
        app: my-apps
    spec: 
      containers: 
        - name: my-container
          image: nginx 
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata: 
  name: my-first-service
  namespace: my-namespace
spec: 
  type: NodePort
  selector:
    app: my-apps
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
