apiVersion: v1
kind: Pod
metadata:
  name: pod-exe
  labels:
    app: myapp
spec:
  containers:
    - name: my-pod
      image: nginx
      ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata: 
  name: my-first-service

spec: 
  type: NodePort
  selector:
     app: myapp
  ports: 
    - port: 80
      targetPort: 80
      nodePort: 30080   
