apiVersion: apps/v1
kind: ReplicaSet
metadata: 
   name: my-rc
   

spec: 
   replicas: 3
   selector: 
      app: my-rco
   template: 
       metadata:
          labels:
            app: my-rco
       spec:
           containers:
               - name: my-container
                 image: nginx
                 ports: 
                    - containerPort: 80
---

apiVersion: v1
kind: Service
metadata:
    name: my-svercice
    labels: 
      app: my-rco
spec:
   type: NodePort
   selector:
     app: my-rco
   ports:
    - port: 8080
      targetPort: 80
      nodePort: 30082       