apiVersion: v1 
kind: Service
metadata:
   name: statefulsvc
   
spec:
   selector:
       app: my-apps
   ports:
       - port: 80
         targetPort: 3306

   clusterIp: None

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
   name: my-svs
   
spec:
   replicas: 3 
   selector:
      matchLabels:
          app: my-apps
   serviceName: statefulsvc
   template: 
       metadata:
           labels:
              app: my-apps
       spec:
           containers:
              - name: my-container
                image: mysql
                ports: 
                  - containerPort: 3306
                env:
                  - name: MYSQL_ROOT_PASSWORD
                    value: omkar123  




   




      











         
